# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"query": "01_activation.ipynb",
         "WolframTester": "01_activation.ipynb"}

modules = ["functional.py"]

doc_url = "https://LandskapeAI.github.io/deeptest/"

git_url = "https://github.com/LandskapeAI/deeptest/tree/main/"

def custom_doc_links(name): return None
