# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://LandskapeAI.github.io/deeptest/"

git_url = "https://github.com/LandskapeAI/deeptest/tree/main/"

def custom_doc_links(name): return None
